version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: medatus
      MONGO_INITDB_ROOT_PASSWORD: medatus

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: medatus
      ME_CONFIG_MONGODB_ADMINPASSWORD: medatus
      ME_CONFIG_MONGODB_URL: mongodb://medatus:medatus@mongo:27017/
  my-app:

    depends_on:
      - mongo
    build:
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    env_file:
      - .env